### ISSUE TITLE
File exclusions are ignored

### ISSUE THREAD

**Issue by robosung** [reviewdog/action-detect-secrets#10]
In an effort to reduced the scan time (currently at ~5min), we added file exclusions to detect_secrets_flags as illustrated below.

![Chore_test_reviewdog_by_robosung_·_Pull_Request__18_·_teamexos_heart-admin](https://user-images.githubusercontent.com/471863/116742174-ddc35580-a9ab-11eb-98db-4dd722085a5e.png)

Unfortunately, it appears that the exclusions flags are being ignored.  

With exclusions, it should be running around these ranges.

> real	0m13.963s
> user	0m26.986s
> sys	0m7.150s

**Comment by levonet** [comment]
Try to remove quotes from arguments. This is similar to the problem in detect-secrets.
Additionally, I suggest ignoring the .git folder.

**Comment by robosung** [comment]
Thanks, that did the trick.

`--all-files --force-use-all-plugins --exclude-files src\/vendor --exclude-files src\/nov`
